# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: ImageCoDe
short_description: Leaderboard for the vision-and-language benchmark ImageCoDe
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: The best overall accuracy (on all static and video examples) on ImageCoDe.
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2023-01-01 00:00:00
end_date: 2028-05-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Total Accuracy", "Video Frame Accuracy", "Static Image Accuracy"],
        "default_order_by": "Total Accuracy",
        "metadata": {
          "Total Accuracy": {
            "sort_ascending": True,
            "description": "Accuracy of predicting the correct images from all image sets.",
          },
          "Video Frame Accuracy": {
            "sort_ascending": True,
            "description": "Accuracy of predicting the correct images from image sets that contain video frames.",
          },
          "Static Image Accuracy": {
            "sort_ascending": True,
            "description": "Accuracy of predicting the correct images from image sets that contain static images.",
          }
        }
      }

challenge_phases:
  - id: 1
    name: Test Phase
    description: templates/description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2023-01-01 00:00:00
    end_date: 2028-05-31 23:59:59
    test_annotation_file: annotations/test_annotations_testsplit.json
    codename: test
    max_submissions_per_day: 1
    max_submissions_per_month: 10
    max_submissions: 20
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
        options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
